services:
    mysql:
        image: mysql:8.0
        container_name: snaptale_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: snaptale
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - snaptale
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            start_period: 30s

    maildev:
        image: maildev/maildev
        container_name: snaptale_maildev
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "1080:1080"
        networks:
            - snaptale

networks:
    snaptale:
        driver: bridge

volumes:
    mysql_data:
        driver: local
